catalog_name: dev
schema_name: datalab_1ai
pipeline_id: 1

parameters:
  eta: 0.3
  n_estimators: 500
  max_depth: 6

ab_test:
  eta_a: 0.02
  eta_b: 0.02
  n_estimators: 500
  max_depth_a: 6
  max_depth_b: 10

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - arrival_year
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type

target: booking_status
